# Generated by Django 2.2.10 on 2020-07-20 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='covid_data',
            name='foot_note',
            field=models.TextField(default='', verbose_name='foot_note'),
        ),
    ]
