# Generated by Django 2.2.1 on 2020-07-30 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_covid_data_foot_note'),
    ]

    operations = [
        migrations.CreateModel(
            name='Uni_data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.TextField(verbose_name='Name')),
                ('State', models.TextField(verbose_name='State')),
                ('Abbreviation', models.TextField(verbose_name='Abbreviation')),
                ('Location', models.TextField(verbose_name='Location')),
                ('Type', models.TextField(verbose_name='Type')),
                ('Founded', models.IntegerField(verbose_name='Founded')),
                ('Location_Address', models.TextField(verbose_name='Location_Address')),
                ('Number_of_students', models.IntegerField(verbose_name='Number_of_students')),
                ('Chancellor', models.TextField(verbose_name='Chancellor')),
                ('Pro_chancellor', models.TextField(verbose_name='Pro_chancellor')),
                ('Vice_chancellor', models.TextField(verbose_name='Vice_chancellor')),
                ('URl', models.TextField(verbose_name='URL')),
                ('Social_media_handle_URL', models.TextField(verbose_name='Social_media_handle_URL')),
                ('Number_of_faculties', models.IntegerField(verbose_name='Number_of_faculties')),
                ('Motto', models.TextField(verbose_name='Motto')),
                ('Programme_offered', models.TextField(verbose_name='Programme_offered')),
            ],
            options={
                'db_table': 'university_data',
            },
        ),
        migrations.DeleteModel(
            name='Covid_data',
        ),
    ]
