# Generated by Django 2.2.1 on 2020-07-30 15:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20200730_1557'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='uni_data',
            table='nigeria_university_data',
        ),
    ]
