# Generated by Django 2.2.1 on 2020-07-30 16:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20200730_1558'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='uni_data',
            table='university_data',
        ),
    ]
