# Generated by Django 2.2.1 on 2020-07-30 16:08

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20200730_1602'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uni_data',
            name='Abbreviation',
        ),
        migrations.AddField(
            model_name='uni_data',
            name='Abbrevation',
            field=models.TextField(default=django.utils.timezone.now, verbose_name='Abbrevation'),
            preserve_default=False,
        ),
    ]
