# Generated by Django 2.2.1 on 2020-08-01 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20200730_1608'),
    ]

    operations = [
        migrations.CreateModel(
            name='Covid_data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_as_of', models.DateTimeField(verbose_name='date_as_of')),
                ('Start_week', models.DateTimeField(verbose_name='Start_week')),
                ('End_Week', models.DateTimeField(verbose_name='End_Week')),
                ('State', models.TextField(verbose_name='State')),
                ('Sex', models.TextField(verbose_name='Sex')),
                ('Age_group', models.TextField(verbose_name='Age_group')),
                ('covid_deaths', models.IntegerField(verbose_name='covid_death')),
                ('total_deaths', models.IntegerField(verbose_name='total_death')),
                ('pneumonia_deaths', models.IntegerField(verbose_name='pneumonia_deaths')),
                ('Pneumonia_andCovid_deaths', models.IntegerField(verbose_name='Pneumonia_andCovid_deaths')),
                ('influenza_deaths', models.IntegerField(verbose_name='influenza_deaths')),
                ('pneumonia_influenzaAndcovid_deaths', models.IntegerField(verbose_name='pneumonia_influenzaAndcovid_deaths')),
                ('foot_note', models.TextField(default='', verbose_name='foot_note')),
            ],
            options={
                'db_table': 'covid_timeseries',
            },
        ),
        migrations.DeleteModel(
            name='Uni_data',
        ),
    ]
